### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by MaherJendoubi** [Microsoft/IIS.Administration#1]
Hi,

When I do Ctrl+F5, I get this issue 
![image](https://cloud.githubusercontent.com/assets/1798510/18257952/b046c4f8-73cc-11e6-816f-4a8f710dd162.png)

Thank you

**Comment by jimmyca15** [comment]
It looks like IIS Express is not letting you override the Windows authentication settings. If you are developing with Visual Studio you should have a .vs folder at the root of the repository. In .vs/config/applicationhost.config the line that says
`<section name="windowsAuthentication" overrideModeDefault="Deny" />`
should be changed to
`<section name="windowsAuthentication" overrideModeDefault="Allow" />`

**Comment by MaherJendoubi** [comment]
@jimmyca15 I changed it but I get a popup for credentials. I put my correct login and password but it popups again!

**Comment by jimmyca15** [comment]
The default settings require you the user to be in the 'Administrators' group or 'IIS Administrators' group to access the API. Even if you are part of the 'Administrators' group you may have this issue. This is due to the default security policy for windows. Here are some solutions and an explanation.

- Log on with the Builtin Administrator account.
- Create the "IIS Administrators" group and add yourself to it.

By default the API requires you to authenticate as an Administrator on the local machine. The default security settings of Windows prevent elevation into the Administrators group through remote authentication unless it is the builtin administrator account. Since this API is running on a web server, all authentication is remote even if you are authenticating on the local machine. The local security policy can be changed to allow the elevation (not recommended) or a local group can be added specifically for IIS Administration. During installation we create the 'IIS Administrators' group which is specified in the appsettings.json file as an Administrative group.

**Comment by shirhatti** [comment]
@jimmyca15 Does it make sense to recommend folks run this script https://github.com/Microsoft/IIS.Administration/blob/dev/scripts/setup/activedirectory.ps1 even for dev time scenarios? Sounds like this might be a common problem

**Comment by jimmyca15** [comment]
@shirhatti I agree. At the least we can have a configure script to alleviate this issue. I'll look into hooking it   up gracefully into the dev workflow.
