### ISSUE TITLE
Renew the self-signed cert used by the API

### ISSUE THREAD

**Issue by drago-draganov** [Microsoft/IIS.Administration#119]
The setup always reuses the existing API cert (including self-signed cert).

With cert expiration of 1 year it's easy to hit the limit.
As minimum the setup should renew API's self-signed certificate if the current is close to expire (< 2-3 months.)

**Comment by jimmyca15** [comment]
Replacing the IIS Administration API certificate if it has less than 3 months left sounds like the best approach. 

The installer should log that the certificate is being replaced. We can do this by adding a verbose log entry to the PowerShell installation script.

**Comment by jimmyca15** [comment]
Closed by #123

**Comment by jimmyca15** [comment]
The solution to this issue was creating a new certificate rather than deleting the existing _Microsoft IIS Administration Server Certificate_

If the server already has a _Microsoft IIS Administration Server Certificate_ then a new certificate will be created with the format _Microsoft IIS Administration Server Certificate {YEAR}_
