### ISSUE TITLE
Incorrect permissions set

### ISSUE THREAD

**Issue by EatonZ** [Microsoft/IIS.Administration#129]
On a fresh Windows Server 2016 + IIS Administration 2.1.0 installation, there appears to be an issue where incorrect permissions are set that prevent the account that installed it (in this case, Administrator) from modifying the various .json files in the config folder.

Of course, I could take ownership of the files to fix the issue, but it doesn't seem like something that I should have to do.

![permissions](https://user-images.githubusercontent.com/3020941/29483301-596013a4-8471-11e7-9b5f-af2254559dea.png)

**Comment by jimmyca15** [comment]
@EatonZ 
This is by design. The contents of .json files are the basis of all the security in the application. If Administrators wish to make changes to these files they must take ownership and be explicit about they're intentions.

We will be adding an API endpoint to configure application settings so in the future this should not be an issue.
