### ISSUE TITLE
FileId in Webapp

### ISSUE THREAD

**Issue by kim182** [Microsoft/IIS.Administration#178]
There should be a "file_info" item associated with webapps (as websites), so it would be easier to access its files.

**Comment by jimmyca15** [comment]
@kim182 

The file_info resource was added to the web sites because web sites act like the root to a virtual file system. Since applications do not share such significance, the file_info object is not used in web applications.

It is still possible to get the file_info object that an application resides in by using the following route:

```
 /api/webserver/files?website.id=<id of parent web site>&path=<path to application>
```
Since an application contains the id of its parent web site, and also its path relative to the web site, the url can be properly constructed after querying the application.

Would this be the ease of access you were looking for?
