### ISSUE TITLE
Unable to configure application: appsettings.json in read-only location

### ISSUE THREAD

**Issue by trendzetter** [Microsoft/IIS.Administration#180]
The installer drops the files in c:\program files\ which causes the appsettings.json to be read-only even for admins. The installer sets the app with only the user running the installer as admin. Result: No means to add admins.
I found no means to override the path. Building from source might be possible but seems still experimental.

**Comment by jimmyca15** [comment]
The reason that the appsettings.json is appearing as read only is that only the SYSTEM account is given write access and then system is made the owner of the file. 

In order to update the permissions for the file, first an administrator should take ownership of the file. Then the administrator can manipulate the ACLs.

Here are two command line tools that can be used to take ownership and then grant access to administrators

```
takeown /f "C:\Program Files\IIS Administration\2.2.0\Microsoft.IIS.Administration\config\appsettings.json" /a 
icacls "c:\Program Files\IIS Administration\2.2.0\Microsoft.IIS.Administration\config\appsettings.json" /grant Administrators:(M) 
```

**Comment by trendzetter** [comment]
That does work very nicely. Thanks for the handy workaround. I was thinking in that direction but I wasn't sure of the exact rights needed and how to get them in place.
