### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by marshallford** [microsoft/IIS.Administration#192]
Hello,

I'm curious if this project is still getting time from MSFT employees. I'm considering installing on 200+ servers and treating it as a source of truth for an internal project. Any roadmapping/future plans for this project?

Thanks.

**Comment by shirhatti** [comment]
The short answer is YES.

A more nuanced answer is that we view the combination of IIS.Administration and https://github.com/microsoft/IIS.WebManager as THE TOOLS to manage IIS going forward.


Unfortunately I don't have a roadmap to share, but our currently our two highest priority items are-
- Integrate with [Windows Admin Center](https://docs.microsoft.com/windows-server/manage/windows-admin-center/understand/windows-admin-center)
- Improve accessibility of IIS.WebManager

Both of these priorities should be accurately reflected by the activities across these repos.

**Comment by marshallford** [comment]
Follow up question: My plan going forward is to replicate a single appsettings file and single API token across all of the IIS servers I am managing to essentially treat 200 instances of the API as one (with different FQDNs anyway). Managing an ever changing mapping of server name to token seems awful, but from a security perspective having one "master" key seems terrible too. Any thoughts into how I can use the two projects you mentioned to avoid feeling like I'm managing 200 APIs?

Thank you for the quick reply and all the work you do.

**Comment by shirhatti** [comment]
Paging @jimmyca15 for suggestions

**Comment by jimmyca15** [comment]
@marshallford 

Are you using IIS shared configuration?

Having a single credential managing a server farm wouldn't be a new concept. IIS has shared configuration capability and it is ultimately managed from a single machine. I do not see any concerns using a single API key in a server farm. 

When it comes to planning out credentials, an important piece is rotation. When using the API Key for management a period should be set out for rotating keys. If the rotation is automated it could even be done on a monthly basis. 

The API supports the ability to generate API Keys during runtime, however it is also possible to generate an API Key with a PowerShell script before starting the API and then placing it in the API's configuration. To do this on a farm the flow would look like this:

1. Generate API Key (Keep it secure, this will be used to access the API).
2. Install IIS Administration.
3. Add generated API Key to the api-keys.json file in the installed IIS Administration's config folder.
4. Access API with the generated API Key.

Note, API Key security is a meets-least-requirements security policy. The IIS Administration API also comes with Windows Authentication enabled to add more complete protection.

For the UI counterpart to IIS.Administration known as IIS.WebManager (https://manage.iis.net) the story is not so complete. We have not yet added a way to group servers and manage them simultaneously. Any modification of a server would have to be done individually. 

Using shared configuration would prevent the need to manage server's individually since all the servers would share the same settings. Shared configuration combined with content served from a shared storage location provides a way to uniformly manage a farm.

**Comment by marshallford** [comment]
@jimmyca15 Thanks for the info. I assume step one in the flow you described would only be done once per farm/cluster (just double checking)? In addition, I'd like to avoid windows auth to allow easy access for clients written in dotnet core or node, but yes that makes sense from a security perspective.

Is managing shared config or managing a group of servers a different way on the roadmap for IIS.WebManager? Maybe a read-only option for collecting data from multiple servers from one endpoint?

**Comment by jimmyca15** [comment]
@marshallford 

Yes, if you would like to use a single API Key for the entire farm then you would only generate that key, yet you would place it in all of the installations' _api-keys.json_ files.

It is possible to remove the windows auth requirements by modifying the settings of the application. If this is done then only API Key authentication is used. 

Managing groups of servers is an important goal. Currently there are a couple of features ahead of that on the road map. The intent has been to make the single server use-case complete and then consider multi-server functionality as you have described.

**Comment by trondhindenes** [comment]
@shirhatti could you reconfirm that this is being maintained? We're seriously considering putting it in our base image for IIS, but since it's still requiring .Net core 1.1 and there seems to be holes in the documentation (especially around installation, actual requirements etc) I'm very sceptical. Not looking for a roadmap, but since most of the code in the repo hasn't been touched in a year along with the outdated .Net Core dependency, it very much feels abandoned.

If there is activity in this repo: What are the plans for at least getting it updated to run on .Net core 2.0? I'm very reluctant to install older .Net core on our servers

**Comment by shirhatti** [comment]
@trondhindenes A goal of IIS.Administration is to minimize churn in the runtime. We didn't require any new features in 2.x and ergo we did not update. .NET Core 2.1.5 was the first designated LTS release (and was granted this designation on 10/02/2018) in the 2.x wave of releases. Given that this LTS designation is relatively new, we are currently evaluating that. .NET Core 1.1 is still supported till June 27, 2019.

Here's link to the .NET Support policy- https://www.microsoft.com/net/platform/support-policy

**Comment by marshallford** [comment]
@shirhatti I share the same 1.1 version concern as @trondhindenes. In addition, .NET Core 2.1.5 [was not](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.3/2.1.3.md#213-declared-lts) the first designated LTS release. The download page is confusing and removes the LTS badge from previous patch versions in the table as per the [support policy](https://www.microsoft.com/net/platform/support-policy). 2.1.3 has been out for a couple of months now, is it time to consider 2.1.x?

**Comment by shirhatti** [comment]
> NET Core 2.1.5 was not the first designated LTS release.

@marshallford My apologies, I stand corrected.

We really appreciate the feedback. We will definitely accelerate our move to 2.1.x

**Comment by shirhatti** [comment]
cc @bariscaglar

**Comment by trondhindenes** [comment]
@shirhatti any timeframe on 2.1.x support?

**Comment by shirhatti** [comment]
@trondhindenes Jan/Feb 2019

**Comment by EatonZ** [comment]
@shirhatti Any date set yet for the next release?
