### ISSUE TITLE
Q: Request payload

### ISSUE THREAD

**Issue by Peperud** [microsoft/IIS.Administration#199]
Are there any plans to expose more request data - headers, body and all?

Less on the administration/configuration and more on the monitoring/troubleshooting side.
It would help when investigating "trouble" requests.

**Comment by jimmyca15** [comment]
No. Do you have something in particular in mind?

**Comment by Peperud** [comment]
We see sometimes requests that appear to be stuck for a long time, consume/hold resources etc. It would help investigating these if we know not only the URL, but the whole request. 
We could do more with logging, though on a busy server, extensive logging might be too heavy performance wise.
Presumably a call to a management/monitoring API can be much more efficient because it would just take a snapshot at the time of the call and only for the requests we're interested in.

**Comment by jimmyca15** [comment]
I see, you are talking about the requests endpoint that provides information about the requests currently executing on the server. It is good to hear that there is interest in this. We have considered features such as the ability to take dumps based on requests, and since there is interest we certainly can evaluate adding improvements to that endpoint.

**Comment by Peperud** [comment]
Exactly. Thank you for considering this.

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
