### ISSUE TITLE
Is it possible to set Preload Enabled on a site via the API?

### ISSUE THREAD

**Issue by ddivita** [microsoft/IIS.Administration#225]
I would think this would be on the website level, but I am not seeing as a property. I also tried going into the modules for the ApplicationInitializationModule, but I did not see any settings there.

**Comment by pope13** [comment]
In IIS, I think PreLoad is an attribute of **Application** not **Site**.  I do not see a way to change it through the API though.

**Comment by shawnmdell** [comment]
In IIS, preLoadEnabled is an attribute of application. However, you can access the ApplicationDefaults through the Site object to set the preLoadEnabled attribute (instead of referencing each application in a site). Should I look into updating the current post/patch methods in SitesController, or create an entirely separate method?

**Comment by shawnmdell** [comment]
To set preLoadEnabled attribute: mySite.ApplicationDefaults.SetAttributeValue("preLoadEnabled", true);

Can be done on individual application objects as well: myApp.SetAttributeValue("preLoadEnabled", true);
