### ISSUE TITLE
Getting HTTP Error 502.5 - Process Failure when trying to get AccessToken

### ISSUE THREAD

**Issue by pieterdv** [Microsoft/IIS.Administration#62]
Hi,

As an experiment i'm trying to run the Administration API in a NanoServer Docker Container. I got through the setup process and the API seems to be running. When I try to connect via https://manage.iis.net/connect and I enter my container ip address, and request an access token i'm able to enter my credentials but then i get the following error:

![image](https://cloud.githubusercontent.com/assets/1443286/22629198/d0afa2e0-ebe1-11e6-9fff-7a357b793b07.png)

So i'm guessing the API is accepting my credentials and then goes into error, i see there are Serilog dll's so maybe something is logged? I'm wondering where I can find these logs, or if anybody has an idea what's going on.

KR

**Comment by jimmyca15** [comment]
The most common cause for this issue is that the service cannot find dotnet.exe

Causes for not finding dotnet.exe:
1. dotnet.exe is not on the **system** path
2. dotnet.exe was added to the system path after IIS was enabled and the computer was not restarted to pick up system path changes

The reason dotnet.exe must be on the path is because of the following line in the _web.config_ file (_IIS Administration\1.0.38\Microsoft.IIS.Administration\web.config_)
```
    <aspNetCore processPath="dotnet" arguments=".\Microsoft.IIS.Administration.dll" forwardWindowsAuthToken="true" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
```

If you do not want to add dotnet.exe to the system path you can change the line to the following.
```
    <aspNetCore processPath="C:\Program Files\dotnet\dotnet.exe" arguments=".\Microsoft.IIS.Administration.dll" forwardWindowsAuthToken="true" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
```
I used the path _C:\Program Files\dotnet\dotnet.exe_ because that is the default install location of dotnet

**Comment by pieterdv** [comment]
You are correct, i forgot to restart my container after installing .net core.

Stupid mistake, sorry for bothering!

**Comment by jimmyca15** [comment]
@pieterdv,

No worries, thank you for filing the issue. Now others with the same issue will be able to find the solution.
