### ISSUE TITLE
Server Farm Management

### ISSUE THREAD

**Issue by mrabernethy** [Microsoft/IIS.Administration#74]
Hi, just wondering if it is possible to alter the status of server farms with the api? If not, is this a planned feature and any time frame for when it would be implemented? Thank you.

**Comment by jimmyca15** [comment]
@mrabernethy 
Do you mind explaining a little bit more what you mean by altering status?

So far we have been focused on building the API so that it is fully functional for administering a single web server. The next step is to optimize server farm scenarios. We have features planned to help improve this experience including **Shared Configuration** (#66) and the **Central Certificate Store** (#41). We will also be looking into methods that will allow us to require communication with only one API endpoint to target any server in a server farm. We will be working on the performance metrics that we expose through the API and want to make this a valuable endpoint that can be used to monitor web farms.

**Comment by mrabernethy** [comment]
@jimmyca15 
I am making a tool to aid in automating deployment. I want to automate taking a server offline to deploy the system to it, then bring it online and take a second server off line. The servers are reverse proxies using application request routing, and are not using shared certificate stores or shared configuration. 
![microsoftteams-image 4](https://cloud.githubusercontent.com/assets/8562391/24378503/a3b70856-139f-11e7-8022-a7147660c4de.png)
![microsoftteams-image 18](https://cloud.githubusercontent.com/assets/8562391/24378514/af22709a-139f-11e7-9d52-c683fd15c06f.png)
Thanks for your help.

**Comment by jimmyca15** [comment]
The API can be used to stop the IIS service. If this is what you mean by take server offline then it supports the scenario that you are describing.

**Comment by mrabernethy** [comment]
@jimmyca15 
Thanks again for your help - I just found how to stop an entire server. But is there a way to stop individual server farms? We are using Application Request Routing (ARR) for load balancing (https://www.iis.net/downloads/microsoft/application-request-routing). Thank you.
![microsoftteams-image](https://cloud.githubusercontent.com/assets/8562391/24484490/fd0f76e2-155a-11e7-8914-08c0ffbbe77f.png)

**Comment by drago-draganov** [comment]
@mrabernethy
We are planning to add support for ARR in IIS Administration API in future releases.

**Comment by jimmyca15** [comment]
This is a request for ARR support through the IIS Administration API. We will track this here #79.
