### ISSUE TITLE
Viewing FREB logs falls back to Basic Authentication

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/IIS.Administration#96]
Click on XML Freb file opens new windows and prompts for basic authorization credentials to authenticate.

**Comment by jimmyca15** [comment]
Which version of the API do you have installed and are you using the default settings for Windows Authentication, access token etc?

**Comment by artisticcheese** [comment]
Running in container with latest version of iisadmin and use settings which i setup earlier inside containers. Clicking on FREB file works but choosing to download it prompts username password. Here is screen capture 
[2017-06-08_15-26-58.zip](https://github.com/Microsoft/IIS.Administration/files/1062322/2017-06-08_15-26-58.zip)

**Comment by jimmyca15** [comment]
If you perform that action with the chrome developer tools open (F12) it will show you which request prompted the need for credentials. Can you try that out?

**Comment by jimmyca15** [comment]
The network tab of the developer tools should be selected.

**Comment by artisticcheese** [comment]
here is screen capture. 
[2017-06-08_15-42-52.zip](https://github.com/Microsoft/IIS.Administration/files/1062364/2017-06-08_15-42-52.zip)

**Comment by jimmyca15** [comment]
Great thanks. I'm looking at this right now.

**Comment by jimmyca15** [comment]
@artisticcheese,

The IIS Administration API requires an authenticated user to be able to download files. Because the _/downloads/_ endpoint does not require an access token and the API as a whole has been configured to not require Windows Authentication the request is treated as unauthenticated and being blocked. Currently there is no work around for this, and using the _/downloads_ endpoint will not work without Windows Authentication. However, the content for the file can still be retrieved through the _/api/files/content_ endpoint because it requires an access token. This is how the content is displayed in the UI when you open the file.

We are currently working on a 2.0 release which will have multiple changes to the Windows Authentication settings for the IIS Administration API. In this release the _/downloads_ endpoint will work when Windows Authentication is not required.

**Comment by artisticcheese** [comment]
When 2.0 release will be done will download URL be changed? My docker file has hardcoded value for location of IISAdmin.exe.

**Comment by jimmyca15** [comment]
The download URL will not be changed for the 2.0 release.

**Comment by jimmyca15** [comment]
This was fixed in the 2.0 release.
